name: py4wrds
channels:
  - conda-forge
dependencies:
  - geopandas
  - h5netcdf
  - jupyter
  - jupyter-book 
  - leafmap
  - localtileserver
  - matplotlib
  - netcdf4 
  - numpy>=2.0.0
  - openpyxl
  - pandas>=2.0.0
  - pip
  - rasterio
  - rioxarray
  - xarray