name: py4wrds
channels:
  - conda-forge
dependencies:
  - pandas
  - matplotlib
  - numpy
  - openpyxl
  - xarray
  - jupyter
  - geopandas
  - rasterio
  - rioxarray
  - netcdf4 
  - h5netcdf
  - pip:
      - jupyter-book