name: py4wds
channels:
  - conda-forge
dependencies:
  - geopandas
  - git
  - numpy>=2.0.0
  - pandas>=2.0.0
  - pip
  - pyarrow
  - python=3.12
  - rasterio
  - scipy
  - pip:
      - humanize
      - ipywidgets
      - jupyter-book
      - jupyterlab
      - matplotlib
      - notebook
      - pillow
      - requests
      - seaborn
