name: py4wrds
channels:
  - conda-forge
dependencies:
  - geopandas
  - h5netcdf
  - jupyter
  - leafmap
  - localtileserver
  - matplotlib
  - netcdf4 
  - numpy >=1.26.4
  - openpyxl
  - pandas 2.*
  - pip
  - rasterio
  - rioxarray
  - xarray