name: py4wrds
channels:
  - conda-forge
dependencies:
  - geopandas
  - h5netcdf
  - jupyter
  - leafmap
  - localtileserver
  - matplotlib
  - netcdf4 
  - numpy
  - openpyxl
  - pandas
  - pip
  - rasterio
  - rioxarray
  - xarray
  - pip:
      - jupyter-book