name: py4wrds
channels:
  - conda-forge
dependencies:
  - certifi
  - geopandas
  - h5netcdf
  - jupyter
  - leafmap>=0.39.0
  - localtileserver
  - matplotlib>=3.10.0
  - netcdf4 
  - numpy>=2.0.0
  - openpyxl
  - pandas>=2.0.0
  - pip
  - pip-system-certs
  - python>=3.12
  - rasterio
  - rioxarray
  - xarray
  - seaborn>=0.13.2
